In [38]:
import numpy as np
docs=['go india','india india','hip hip hurray','jeetega bhai jeetega india jeetega','bharat mata ki jai','kohli kohli','sachin sachin','dhoni dhoni','modi ji ki jai','inquilab zindabad']


In [39]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()
tokenizer.fit_on_texts(docs)

In [40]:
len(tokenizer.word_index)

17

In [41]:
sequences=tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [42]:
from tensorflow.keras.utils import pad_sequences
sequences=pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [43]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding
model=Sequential()
model.add(Embedding(input_dim=18, output_dim=2, input_length=5))
model.summary()


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.compile('adam','accuracy')


In [45]:
pred=model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[[-0.01133252  0.00960695]
  [-0.00210876  0.03163571]
  [-0.02998055 -0.04709902]
  [-0.02998055 -0.04709902]
  [-0.02998055 -0.04709902]]

 [[-0.00210876  0.03163571]
  [-0.00210876  0.03163571]
  [-0.02998055 -0.04709902]
  [-0.02998055 -0.04709902]
  [-0.02998055 -0.04709902]]

 [[ 0.01309276  0.01440344]
  [ 0.01309276  0.01440344]
  [-0.01892284  0.03065935]
  [-0.02998055 -0.04709902]
  [-0.02998055 -0.04709902]]

 [[-0.01823121  0.00959652]
  [ 0.03829873 -0.02597246]
  [-0.01823121  0.00959652]
  [-0.00210876  0.03163571]
  [-0.01823121  0.00959652]]

 [[ 0.00416825 -0.00792294]
  [-0.04979632 -0.02013184]
  [-0.01923356 -0.04544238]
  [ 0.04051175 -0.04961172]
  [-0.02998055 -0.04709902]]

 [[ 0.04620366  0.03265141]
  [ 0.04620366  0.03265141]
  [-0.02998055 -0.04709902]
  [-0.02998055 -0.04709902]
  [-0.02998055 -0.04709902]]

 [[-0.00319187  0.04748514]
  [-0.00319187  0.04748514]
  [-0.02998055 -0.04709902]
  [-0.02998055 -0.04709902